dist: trusty
language: java
install: "/bin/true"
script:
- mvn clean install -q -B
deploy:
- skip_cleanup: true
  provider: script
  script: "./deploy"
  on:
    branch: master
- skip_cleanup: true
  provider: script
  script: "./deploy"
  on:
    tags: true
env:
  global:
  - secure: tP6AcLjUJYchqSlutC9D18vcftXSrA+y+7OYiA8zkFrSxhv62avHtNH9W5AULHE9KeEedClGiK2ugI4yYOtCeinj3k2YtuSxSRc7sTFdzw51ocGSjlHbDQuVyb1on2MV4uiabZM7NlmEPg3G6FKMU+R2pNmJmaMYN+ceNod4Iw5pPbUHK/81UxT6sZJrAZsxwvqDczNVlru+EgfdrWl37zz5lGl9xXuDJcmUwRo7iF5JsEQNBbl+bjMjOfJNnUM1USqhdXoL/k3KmKInQTVHcsa7F1rfCnPpG8hCYpPBfNcCYRjeQJkusiPn8ZWP/C7Ke1fC+J5u9r1xp26XvDUDMKG3994gc0/7QMvGL3qgmPZOXmhhq+UlmwnyaTbgTNEt/Y9aKj9FuW+6YzYy4EgV58pBopyT8xdthFBldDgMTit4q71FnxDlcxlHW2OqNefpQh77573rV0UdhVmA5ROgZ7IwCgzYadtcVswRgKunAWX7L/X6kdNeWaXKesSPK8JlX0JXDXu1od4R5XMFrnX4iDrviw8y1+Azwp7+ox6oLF7Ph2lhMiy6yW8zCL0yNvDpnsYRkwPmTMzpa7j6lVeHDg2p0JRKWOe8L0YEElkiuhc93vhSAGlSALqXuFGL1m3LOxcrVUysStVVTAqFum+OzIKE9hy6NxeS7Em3d2yUHOs=
  - secure: LszzBLUQOXzIunAT2u11NX58Jmdrdt1fGA4Yu6bA0pc6R2INeztJsFNJSdMHejA+mC+akoawhn7Bt2065zHfJy3ifN7/7pQu5Uuvfs07N9SoGHcAUEmS7IoKTBvGxibLkxCXKgWmLfDwccp31Uc2tBlT84mMrvdlo79HAaqdFeIqwRBEgca2HqSeJVSmYL4QAinWXuvpiXiHBbuH1qjbHSjYy0u2/pS7S/2UzsvaubKGLrq2V6w8l2VTfeXX+OdLWUUenjSo9jf7pQh1MfG1kKXkrQVg7aEDBoRg0WS/YF0XvwwbmjIlAFDuwt1kRX5EuBbS0vZnUvYd3/Z8NqkmqHLKAK9kxkaui9gaY9H2TLF/spTZ9+vWTdPN8XxOCaVmRLGezGAbUJJR4QNNxy+sfTY9WvnKIe8Zo9r2WGx/AoFKmgs4Xrre5NTYCJNVzV6O6HwxVosPVIRHJDvWFgUDMoAf3KzctsGYy401cIaSy1fsbC0mZQKUHmwlGvP+N6u9hW1Grg9raNEA6Bgfyo56emrAOfDaAMrdAcxby9xRAQs/7H45w7UeB6gWNqwytwBjqRNmcybbQy0OLwbY4bEcIB0/FYXt2qpOz+3sJXtF+nh6vT8fFPNykb/MACFHw3yiH+w+038mTutLw/jyQzxvWWo72u/hCyd/Z5BvYhzn8nQ=
  - secure: i4v4vEVucmELKZ8CpIDwGrxLRWAT+WIHgdwccMWaKlWzHjnnsFX8OXocMIQ0hL/m92r201AZtpIC1r6krSvFVU5xkMlhaMklOhVmx+/l09geJQRg2AV0aHd9bvXo3GuL7bCJA7kFuQor12dLirELhGiP15iVxM/OKn+OQxUW8HYB6u4GRXr/gPQejAMjzFH/1zB9eCphSKxVLTCexyt8H2PHKgjQY/JHj1Idd2bC75Dn4ug/F2V8R7w/5c+bDS5uPWimG4p7kf/3eyD1KR7QgYlxzPznVBkQSSaW3ZaFj41Wnbv/aOhSexR9j0WxT6nm+1ds8C8FrCgmBXGwCHqi5NIxBSQb3+nc6b5A39TpPeUtFNyXFVX7mxwr9qPkI73kLdZzIk+4dXDoh2HB2PF5FjxVVWDug/qx0uSFeeaNsQdGVAsvVbWDvVVRK3+FTVFrXTzFMoRrY53au4P6phWP8/CsA0FTdAM3718PUf1aBYWGuMY08dRyFeEo4+AZ4hd67R4WRuaPtAzBYWl7k5ynGGrk2pzwrs0895ILVM/tSjea8pnnU0wijx4FuPttDAfjL3XueQg50EHIJgA19YM0tLyZJWZvkm/luAyzdDcMNZZgfvan24TbyHiQCgrwurXE9IPzuzZUqWHgxWoETkccJrFFImlLu7Znp5gqijjvtog=
  - secure: fAXJ7jB1uBZclK8UdAgxL50ZzAIdOuEjHxkq5vIp2AEKe58fy4G3sP715sb2XpEqQpf3Rfkd7ueuHYrAWRjCYzqWFBlfVyQELPtOTu4EyCIvVPdtSdkezbMsCa+/mCn4yOqExkqJ39FbnTL9U2ih8OwmveY5SkmM9Tatid5wcNgs4ZMvvO4nXPfdb4YJosalr+8pThPX7Rdz2rDqROrCvOps98xYecW6k+tU+LVa3F6h9lkwIF2NsEKZXBLCFxlzHhwv0LzGJWz5nzZYdxCOfXO7czCdXh+fKX3yZ3vSzZvNh6EDORMHu6OKdCLVU8/6AoY5DASPTqCTez7OT9iBpLBKCxIu44leTAovk/hYFD6TFDjdxOrqu4AnBoI+f4w8hbcyFFtTw7wVifk7RRnqxif/spRzmDB6iu4g1MIlqQWklFP8BZSV23Ph91BzdeG6rd6n/mzmHBTsdxqqpf1knwiIzHUTz6fC4i72GkDga44j018RdRZT3/yfeoNM/vrXCjyiknCrmBY1QQww4iWgudpHXqZi+qXbYC1pwbEbpZuBCjsu03Zte3LrUkSLba3KB2CBMYs92TNhmXTYrlDzJUjOiPiUDZmHVlEuSpaQ6v1DmAA4OVhYU01uk4I4MBEPdP1VCRUlZnFMAQ/rhYtwVBol0ctA5rvF1gx3Cph6hLA=
before_install:
- gem install bundler
- openssl aes-256-cbc -K $encrypted_4f0d00631887_key -iv $encrypted_4f0d00631887_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
